const router = require('koa-router')();
const mongoController = require('./mongo.controller');
const elasticController = require('./elastic.controller');
const mongoEsController = require('./mongo-es.controller');

router.post('/WebsiteFocusInit', mongoEsController.WebsiteFocusInit);
router.post('/initWebsites', mongoEsController.initWebsites);
router.post('/HomePageInit', mongoEsController.HomePageInit);
router.post('/infoDetail', elasticController.infoDetail);
router.post('/getInfoList', elasticController.getInfoList);
router.post('/keywordSearch', elasticController.keywordSearch);
router.post('/recommend', mongoEsController.getRecommend);
router.post('/relatedSearch', elasticController.relatedSearch);
router.post('/moreInstance', elasticController.moreInstance);
router.post('/globalSearchHint', elasticController.globalSearchHint);
router.post('/globalSearch', elasticController.globalSearch);
router.post('/getSearchInfos', elasticController.getSearchInfos);
router.post('/getEntityInfos', elasticController.getEntityInfos);
router.post('/columnChange', mongoEsController.columnChange);
router.post('/addUserCollection', mongoEsController.addUserCollection);
router.post('/cancelUserConnection', mongoEsController.cancelUserCollection);
router.post('/exportSites', mongoEsController.exportSites);
router.post('/initForce', elasticController.initForce);
router.post('/updateForce', elasticController.updateForce);
router.post('/siteFocusSetInit', mongoController.userWebsitesInit);
router.post('/siteFocusSetSave', mongoController.siteFocusSetSave);
router.post('/checkNote',mongoController.checkNote);
router.post('/saveNote',mongoController.saveNote);
router.post('/modifyNote',mongoController.modifyNote);
router.post('/openNote',mongoEsController.openNote);
router.post('/getTodayExportSum',mongoEsController.todayExportSum);
router.post('/changeExportLog',mongoEsController.changeExportSum);
module.exports = router;